#!/bin/bash

HEADER="#MadBuilder Configuration#"
FOOTER="#End of MadBuilder Configuration#"
RC=/etc/mozpluggerrc

CONTAIN=`grep "$HEADER" $RC`

if [  -z "$CONTAIN" ]
then
cat <<EOF >> $RC

$HEADER
application/x-mbsvg:mbsvg: MadButterfly SVG
        swallow(Inkscape) : /usr/share/madbutterfly/inkscape/usr/bin/helper_mb.py "\$file"
application/x-h:h: MadButterfly SVG h program
	swallow(gedit) : gedit "\$file"
$FOOTER

EOF
echo Configuration installed to $RC
fi
